---
version: 2

jobs:
  tests:
    docker:
      - image: golang:1.10
    working_directory: /go/src/github.com/gocardless/pgbouncer_exporter
    steps:
      - checkout
      - run:
          name: Run go unit tests
          command: go test -race ./...

  release:
    working_directory: /go/src/github.com/gocardless/pgbouncer_exporter
    docker:
      # We can't use an image from Circle's repo when logging in with our GCR credentials.
      # - image: circleci/golang:1.10
      - image: eu.gcr.io/gc-containers/gocardless/anu-circleci:2018053000
        auth:
          username: _json_key
          password: $GCR_PUSHER_CREDENTIALS
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to GCR
          command: |
            docker login -u _json_key --password-stdin eu.gcr.io <<< "$GCR_PUSHER_CREDENTIALS"
      - run:
          name: Release
          command: |
            CURRENT_VERSION="v$(cat VERSION)"

            if [[ $(git tag -l "${CURRENT_VERSION}") == "${CURRENT_VERSION}" ]]; then
              echo "Version ${CURRENT_VERSION} is already released"
              exit 0
            fi

            go get -u github.com/goreleaser/goreleaser

            git log --pretty=oneline --abbrev-commit --no-decorate --no-color "$(git describe --tags --abbrev=0)..HEAD" -- *.go > /tmp/release-notes
            git tag "${CURRENT_VERSION}"
            git push --tags

            goreleaser --rm-dist --release-notes /tmp/release-notes

workflows:
  version: 2
  pipeline:
    jobs:
      # - tests
      - release:
          requires:
            # - tests
          # filters:
            # branches: {only: master}
